[Feat]: todolist Entity & Repository 구현 -#13
inu-appcenter/server-study-16th pull request #14
Opened 2024-04-07 20:39 UTC by jiyunio

2024-04-10 06:05 UTC, Juser0 approved these changes

2024-04-13 10:48 UTC, NARUBROWN requested changes
확인했어! 답변 남겨놨으니 확인하고 수정해줘!

2024-04-13 10:48 UTC, NARUBROWN commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/member/MemberService.java
> +public class MemberService extends Member {
Entity를 상속 받은 이유를 알고 싶어!

2024-04-13 10:48 UTC, NARUBROWN commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/category/Category.java
> +    private Member member;
Member Entity에서 id에 대한 Field를 
`@Column(name = "memberId")
private Long id;`
이렇게 지정했으니 JoinColumn(name)으로 외래키를 지정할 때는 
JoinColumn name을 `@Column(name= "memberId")`와 동일하게 memberId로 지정해주는 것이 좋아 보여

2024-04-13 10:48 UTC, NARUBROWN commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/member/dto/ChangeUserPw.java
> +public class ChangeUserPw {
이름에 Dto를 넣는 걸 깜빡했네!

2024-04-13 10:48 UTC, NARUBROWN commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/todo/TodoRepository.java
> +    Optional<Todo> findById(Long todoId);
왜 findById를 Override 한 거야?

2024-04-13 10:48 UTC, NARUBROWN commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/todo/dto/TodoDto.java
> +    private String content;
DTO에도 @Lob이 붙어야 해?

2024-04-13 11:19 UTC, jiyunio commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/todo/TodoRepository.java
> +    Optional<Todo> findById(Long todoId);
ctrl+o 단축키 눌러서 이용했는데 @Override 가 자동으로 붙더라

2024-04-13 11:19 UTC, jiyunio commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/member/dto/ChangeUserPw.java
> +public class ChangeUserPw {
추가할게! 고마웡

2024-04-13 11:25 UTC, jiyunio commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/category/Category.java
> +    private Member member;
@JoinColumn에서 name 속성을 "매핑할 필드명 + _ + 참조할 테이블의 기본키" 이렇게 작성하라고 해서 해봤는데 memberId가 프로젝트에서 하나밖에 없으니까 memberId로 지정해도 되는 거야?

2024-04-13 11:35 UTC, jiyunio commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/todo/dto/TodoDto.java
> +    private String content;
클라이언트한테 바로 받는 값이라 앞에서 길이제한 풀어주는 게 좋다고 생각했엉. 근데 여기말고 CreateTodoDto로 바꿔야 할 거 같다

2024-04-13 12:15 UTC, jiyunio commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/member/MemberService.java
> +public class MemberService extends Member {
앗 지워야 할 거 같아..
패키지 전체 수정하기 전에, protected updateUserPw 사용하고 싶은데 member랑 memberservice랑 서로 다른 패키지에  있으니까 적었었어

2024-04-17 05:29 UTC, NARUBROWN commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/todo/dto/TodoDto.java
> +    private String content;
@Lob은 영속성 관련 어노테이션이라 DTO에는 붙이지 않아도 괜찮아

2024-04-17 05:30 UTC, NARUBROWN commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/todo/TodoRepository.java
> +    Optional<Todo> findById(Long todoId);
굳이 없어도 되는 부분인 것 같아! 삭제하도록 하자

2024-04-17 05:31 UTC, NARUBROWN commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/category/Category.java
> +    private Member member;
필드명이 member야!

2024-04-17 20:04 UTC, jiyunio commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/category/Category.java
> +    private Member member;
아 저거 잘못 적었구나 수정할게!!

2024-04-17 20:04 UTC, jiyunio commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/todo/TodoRepository.java
> +    Optional<Todo> findById(Long todoId);
넵

2024-04-17 20:04 UTC, jiyunio commented on contents/todoListAPI/jiyun/src/main/java/com/jiyunio/todolist/todo/dto/TodoDto.java
> +    private String content;
수정할겝

2024-04-29 06:29 UTC, NARUBROWN approved these changes

2024-05-06 00:05 UTC, merged